### ISSUE TITLE
Event details: Favourite FAB state is lost after opening search

### ISSUE THREAD

**Issue by emartynov** [squanchy-dev/squanchy-android#594] opened 2018-10-25 12:42 UTC
Steps to reproduce:
1. open talk
2. favourite it
3. select search from menu
4. close search

Expected:
Talk is favourite

Actual:
Visual state about favourite is cleared

**Comment by rock3r** [comment] 2018-10-25 13:26
I can confirm I can repro this; thanks @emartynov for the report, we'll look into it :)

**Comment by emartynov** [comment] 2018-10-25 14:26
Thanks for the rewording :) Should be super minor and easy to fix.

**Comment by rock3r** [comment] 2018-10-25 14:29
No worries, changed it slightly so it's easier for the team to understand :)

I hope it won't be a big deal, probably some binding of the viewmodel to the UI gets it wrong somewhere in `onResume` — I doubt it'll turn out being specific to search.

**Comment by fourlastor** [comment] 2018-12-13 09:52
@rock3r I can't reproduce it, maybe something changed that fixed this? I tried disabling the persistence and it still works as expected. Not sure what could be the reason this works now.

**Comment by fourlastor** [comment] 2018-12-13 14:33
Ok, I can reproduce with Android 8.1 on an emulator, couldn't on Android 6 (talking to @rock3r it was probably because Android 6 emu doesn't have a standard play services image)

**Comment by rock3r** [comment] 2018-12-15 15:24
Should be fixed in #610

**Closed as completed by rock3r** 2018-12-15 15:24 UTC
Labels: bug
