### ISSUE TITLE
Null pointer when skipped sign in

### ISSUE THREAD

**Issue by vishnus1224** [squanchy-dev/squanchy-android#392] opened 2017-11-07 11:12 UTC
Skip the google Sign In flow.
App tries to load data and crashes.

Here's the log 
com.google.firebase.database.DatabaseException: Problem in DB at path data/days, class class net.squanchy.service.firebase.model.FirebaseDays
                                                                          at net.squanchy.service.firebase.FirebaseDbService$observeChildAndEmit$1$listener$1.onDataChange(FirebaseDbService.kt:88)
                                                                          at com.google.android.gms.internal.zzduz.zza(Unknown Source:13)
                                                                          at com.google.android.gms.internal.zzdwu.zzbvb(Unknown Source:2)
                                                                          at com.google.android.gms.internal.zzdxa.run(Unknown Source:65)
                                                                          at android.os.Handler.handleCallback(Handler.java:789)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                          at android.os.Looper.loop(Looper.java:164)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                       Caused by: kotlin.KotlinNullPointerException
                                                                          at net.squanchy.service.firebase.FirebaseDbService$observeChild$1.invoke(FirebaseDbService.kt:69)
                                                                          at net.squanchy.service.firebase.FirebaseDbService$observeChildAndEmit$1$listener$1.onDataChange(FirebaseDbService.kt:86)
                                                                          at com.google.android.gms.internal.zzduz.zza(Unknown Source:13) 
                                                                          at com.google.android.gms.internal.zzdwu.zzbvb(Unknown Source:2) 
                                                                          at com.google.android.gms.internal.zzdxa.run(Unknown Source:65) 
                                                                          at android.os.Handler.handleCallback(Handler.java:789) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                          at android.os.Looper.loop(Looper.java:164) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by vishnus1224** [comment] 2017-11-07 11:13
Happens with data/venue too. 
I just setup the project yesterday to make some contributions.

**Comment by vishnus1224** [comment] 2017-11-07 18:10
In the `observeChildAndEmit`, the value from DataSnapshot is null 
`val value = dataSnapshot.getValue(clazz)`. So the next step tries to map on this empty value and boom.

**Comment by vishnus1224** [comment] 2017-11-08 10:06
Think this is related to #345. But can be fixed if Error Notification from Observable is handled and some error state is shown in the UI.

**Comment by quiro91** [comment] 2017-11-08 22:24
Hello @vishnus1224 and thanks for opening the issue. We are going to migrate from the Realtime Database to Cloud Firestore, so we will need to rewrite that code eventually. Anyway, looking at the stacktrace I guess the crash is caused by the lack of data in the `data/days` node of the realtime db, as we assume that the days of the conference are not an optional value

**Comment by vishnus1224** [comment] 2017-11-09 09:00
Yeah that's what is causing the issue. I guess it can be closed since that code will be rewritten.
Is anyone currently working on #333.If not then can I work on it ?

**Comment by quiro91** [comment] 2017-11-09 11:20
@vishnus1224 yes, go for it! I'll close this issue, you can assign #333 to yourself and start working on it

**Closed as completed by quiro91** 2017-11-09 11:20 UTC
